### ISSUE TITLE
[Feature]: open left panel by swipe

### ISSUE THREAD

**Issue by gmankab** [KitsunedFox/termux-monet#105]
initially, termux required swiping from the left edge of the screen to the right in order to open the left menu, but in modern versions of android, when you swipe from the left edge of the screen, a backward gesture is triggered

maybe it’s worth making the left panel open on swipe from the middle of the screen to the right

**Comment by kaicsm** [comment]
It seems like an interesting feature, especially for those who use android's gesture system.
Doesn't seem difficult to implement

**Comment by kaicsm** [comment]
This issue has already been opened in the original termux application, this may help you: https://github.com/termux/termux-app/issues/1325

**Comment by gmankab** [comment]
original app last updated more than 2 years ago :)

**Comment by KitsunedFox** [comment]
Fixed in: https://github.com/KitsunedFox/termux-monet/pull/131

**Comment by gmankab** [comment]
@KitsunedFox, can't git it to work on 23df8cc nightly build

https://github.com/KitsunedFox/termux-monet/assets/73340745/af4bad50-0a2b-44b8-a868-37f5decc6263

**Comment by KitsunedFox** [comment]
it doesnt work by swiping the middle of the screen.
but, the back gesture triggers it now.

**Comment by gmankab** [comment]
on, thanks

good enough too
