### ISSUE TITLE
Google Play suggests updating Termux as the official release has a higher version code, it fails

### ISSUE THREAD

**Issue by h0tk3y** [KitsunedFox/termux-monet#139]
### Problem description

The official Termux app received updates on Play Store in May/June 2024, and Termux is now always shown as an out-of-date app that fails to update.

### Steps to reproduce the behavior.

Open Google Play Store "Manage apps & device" menu, then "Updates available", find that Termux is there. 

![Screenshot_20240615_210706_Google Play Store](https://github.com/KitsunedFox/termux-monet/assets/1888526/ab8712c5-191e-4ce6-a49d-687a95910ac7)

### What is the expected behavior?

The Termux-Monet modded distribution should have a version code in a range that is greater than the one used by the official app. 

### System information

* Termux Monet version: 4.38.22
* Is Nightly or Stable?: stable release
* Android OS version: 14
* Device model: Samsung Galaxy S23 Ultra

**Comment by jaredcat** [comment]
upstream just released this branch: https://github.com/termux/termux-app/tree/github-releases/v0.118.1

**Comment by h0tk3y** [comment]
Also see this commit message: https://github.com/termux/termux-app/commit/43317b78c920a48254f8846f5e14b5f873faa271
