### ISSUE TITLE
No true color support

### ISSUE THREAD

**Issue by qiaten** [KitsunedFox/termux-monet#144]
### Feature description

This will only happen on the application of this project
![Screenshot_2024-06-27-03-54-02-85_84d3000e3f4017145260f7618db1d683](https://github.com/KitsunedFox/termux-monet/assets/110800005/1fd13a0a-0ac5-4f7b-bbd4-17e5d981e682)

### Additional information

The above situation will not occur in other derivative versions
![Image_1719431665524](https://github.com/KitsunedFox/termux-monet/assets/110800005/b5471bbd-67b6-452f-9004-a5ba13c9e246)

**Comment by KitsunedFox** [comment]
Remove the last ; before "m"
This is happening because of this recently merged PR: https://github.com/termux/termux-app/pull/4031

Other terminals do parse \e[31;m as \e[31;0m, so... your're resetting the colors before applying them.

try: echo -e "\e[38;2;127;127;127m Hello World! \e[0m"
