### ISSUE TITLE
[Feature]: use nerd font by default

### ISSUE THREAD

**Issue by gmankab** [KitsunedFox/termux-monet#152]
### Feature description

so, there is a lot of bash, fish, and neovim configs, that requires nerd fonts

please consider switching to nerd font by default

### Additional information

-

**Comment by KitsunedFox** [comment]
Not possible. that would require modifying the bootstrap packages to ship nerd fonts directly on .termux folder. Only official termux can do that, i can't maintain a whole packages repo fork without breaking pkg for everyone
