### ISSUE TITLE
[Bug]: Single row extra-keys dislocation

### ISSUE THREAD

**Issue by XiaoBaiNya** [KitsunedFox/termux-monet#153]
### Problem description

My extra-keys are configured as a single line and some keys don't display properly
![Screenshot_2024-06-30-11-37-45-689_com termux](https://github.com/KitsunedFox/termux-monet/assets/87774179/3a47d4d5-8250-4742-99a2-370ec4c6f7da)

### Steps to reproduce the behavior.

Change the extra-keys configuration in termux.properties to a single line

### What is the expected behavior?

Display the correct key
![Screenshot_2024-06-30-11-36-55-418_com termux](https://github.com/KitsunedFox/termux-monet/assets/87774179/6a04e336-4aed-4d98-bb6f-8234295bcc1b)

### System information

* Termux Monet version:0.119.0-beta.1
* Is Nightly or Stable?:Stable
* Android OS version:android14
* Device model:RedmiK60

**Comment by KitsunedFox** [comment]
Will be fixed on the next release. I will make the blurred background match the extrakeys height

For now, disable the blurred background on termux settings until i make a nightly build with this fixed 

and.. whats the name of your keyboard app? i really liked it :)

**Comment by KitsunedFox** [comment]
Fixed in https://github.com/KitsunedFox/termux-monet/commit/e354746a85b2d501194ab9a0cdf058be2e4f5cf5
You can get a release with this bug fixed in https://github.com/KitsunedFox/termux-monet/actions

**Comment by XiaoBaiNya** [comment]
My keyboard app is Baidu Keyboard, I use the theme is SenLinJi's LiangBaiKai, I do not recommend this app because of Software bloat
