### ISSUE TITLE
[Bug]: In dark mode can't differentiate if an extra key is pressed or not

### ISSUE THREAD

**Issue by indrastorms** [KitsunedFox/termux-monet#17]
### Problem description

Title says it all

### Steps to reproduce the behavior.

Enable dark mode tap on an extra key, you can't tell which one is pressed

### What is the expected behavior?

It should be highlighted

### System information

* Termux Monet version: 0.118-16
* Is Nightly or Stable?: Stable
* Android OS version: 12.1
* Device model: poco x3 pro

**Comment by HardcodedCat** [comment]
Screenshot?

**Comment by Indranil012** [comment]
> Screenshot?


https://user-images.githubusercontent.com/48489074/190752004-a192ed0a-12b7-42ad-aa58-bed6c3d8c26f.mp4

**Comment by HardcodedCat** [comment]
Is that v0.118.0-16?
This side padding was removed on a very previous update

**Comment by Indranil012** [comment]
> Is that v0.118.0-16? This side padding was removed on a very previous update

Oh yes, forgot to mention.

**Comment by usernein** [comment]
https://user-images.githubusercontent.com/29507335/206825912-c80215c5-a69c-4de1-9e8b-3610427cc55f.mp4

Same happening to me

**Comment by HardcodedCat** [comment]
ONE UI have disabled monet, just like MIUI

**Comment by MaximumWoahverdrive** [comment]
Termux Monet version: 0.118.0+ee72036 and 0.118.0-33
Is Nightly or Stable?: Nightly & Stable
Android OS version: 14 (UPB5.230623.005.A1)
Device model: Pixel Fold

While it is differentiable on light mode, the visual could be clearer.
Perhaps a background color change instead/in addition to the current text color change?

**Comment by LovecraftianGodsKiller** [comment]
Is this still being investigated?
I have a Z Flip 4 and the highlighting only happens when using light mode.

I'm not bothered by it, I've gotten used to it being that way.

I would like to reiterate what @MaximumWoahverdrive suggested: Changing the background color instead of, or in addition to, the text color change.

**Comment by KitsunedFox** [comment]
Fixed in [v0.119.0-b1-34](https://github.com/KitsunedFox/termux-monet/tree/v0.119.0-b1-34)
