### ISSUE TITLE
[Bug]: dark mode enabled, but termux keys still white

### ISSUE THREAD

**Issue by Luizin5** [KitsunedFox/termux-monet#39]
### Problem description

First, I want to apologize for my bad english.
I enabled dark mode in phone setting, but termux keys still white 
![Screenshot_20230116-185226](https://user-images.githubusercontent.com/83879368/212773337-046564e2-c372-4efd-abfc-071b98c5a8cc.png)

### Steps to reproduce the behavior.

Enabled dark mode.

### What is the expected behavior?

Black Termux keys, like in default termux.

### System information

* Termux Monet version: 0.118.0
* Is Nightly or Stable?: Stable
* Android OS version: 9 
* Device model: moto G6 plus
*

**Comment by M1R47** [comment]
It presents the same error in the app, I don't know if they have currently corrected the error

**Comment by KitsunedFox** [comment]
Fixed in: [v0.119.0-b1-34](https://github.com/KitsunedFox/termux-monet/tree/v0.119.0-b1-34)
