### ISSUE TITLE
[Bug]: for God's enable extra keys transparency and blur

### ISSUE THREAD

**Issue by aicynide** [KitsunedFox/termux-monet#99]
### Problem description

Transparency of extra keys disabled

### Steps to reproduce the behavior.

Extra keys blur is also disabled

### System information

* Termux Monet version:
* Is Nightly or Stable?:
* Android OS version:
* Device model:
*

**Comment by KitsunedFox** [comment]
Currently experimenting with this...
![Screenshot_20240627-001336_Termux](https://github.com/KitsunedFox/termux-monet/assets/103902727/3db2693e-5617-44f8-a96e-c1c6f0237cc0)

**Comment by KitsunedFox** [comment]
Aaaand, Finished! you can test it on the latest Nightly Builds
https://github.com/KitsunedFox/termux-monet/actions/workflows/debug_build.yml
